<?php

class TKT_ElectronicDocumentService extends \SoapClient
{

    /**
     * @var array $classmap The defined classes
     */
    private static $classmap = array (
  'Address.Detailed' => '\\AddressDetailed',
  'Address.Simple' => '\\AddressSimple',
  'Amount' => '\\Amount',
  'ApplicationResults' => '\\ApplicationResults',
  'Building' => '\\Building',
  'Contact.Summary' => '\\ContactSummary',
  'Currency' => '\\Currency',
  'DiagnosticResults' => '\\DiagnosticResults',
  'ErrorMessage' => '\\ErrorMessage',
  'HostCommand' => '\\HostCommand',
  'Identifier.System' => '\\IdentifierSystem',
  'Location.POS' => '\\LocationPOS',
  'Message.Condition' => '\\MessageCondition',
  'MessagingRecords' => '\\MessagingRecords',
  'MessagingSystemRecord' => '\\MessagingSystemRecord',
  'Parameters' => '\\Parameters',
  'POS' => '\\POS',
  'ProblemInformation' => '\\ProblemInformation',
  'ProblemInformationFromLLS' => '\\ProblemInformationFromLLS',
  'ResultRecord' => '\\ResultRecord',
  'Results' => '\\Results',
  'STL_HeaderBase' => '\\STL_HeaderBase',
  'STL_Header.Ack' => '\\STL_HeaderAck',
  'STL_Header.Notif' => '\\STL_HeaderNotif',
  'STL_Header.RQ' => '\\STL_HeaderRQ',
  'STL_Header.RS' => '\\STL_HeaderRS',
  'SecurityTokenCG' => '\\SecurityTokenCG',
  'Street' => '\\Street',
  'Success' => '\\Success',
  'SystemSpecificResults' => '\\SystemSpecificResults',
  'SystemSpecificResultsFromLLS' => '\\SystemSpecificResultsFromLLS',
  'Telephone' => '\\Telephone',
  'TrackingID' => '\\TrackingID',
  'TransactionInfo' => '\\TransactionInfo',
  'UsernameToken' => '\\UsernameToken',
  'Affinity.FrequentFlyer.ED' => '\\AffinityFrequentFlyerED',
  'Amount.Basic' => '\\AmountBasic',
  'Amount.Commission' => '\\AmountCommission',
  'Amount.Commission.Agency' => '\\AmountCommissionAgency',
  'Amount.Commission.Category35' => '\\AmountCommissionCategory35',
  'Amount.Commission.ED' => '\\AmountCommissionED',
  'Amount.Details' => '\\AmountDetails',
  'Amount.Details.CurrencyConversion' => '\\AmountDetailsCurrencyConversion',
  'Amount.Details.ED' => '\\AmountDetailsED',
  'Amount.Details.RateofExchange' => '\\AmountDetailsRateofExchange',
  'Amount.Rate' => '\\AmountRate',
  'Amounts.Commission' => '\\AmountsCommission',
  'Amounts.New' => '\\AmountsNew',
  'Amounts.New.ED' => '\\AmountsNewED',
  'Amounts.RelatedDocument' => '\\AmountsRelatedDocument',
  'ClassOfService.Details' => '\\ClassOfServiceDetails',
  'Code.Approval' => '\\CodeApproval',
  'CurrencyConversion.Details' => '\\CurrencyConversionDetails',
  'Code.BaggageAllowance' => '\\CodeBaggageAllowance',
  'Customer.Traveler.Details.ED' => '\\CustomerTravelerDetailsED',
  'DateRange' => '\\DateRange',
  'Diagnostic' => '\\Diagnostic',
  'DataXML' => '\\DataXML',
  'DynamicCurrencyConversion' => '\\DynamicCurrencyConversion',
  'ElectronicDocument.SearchParameters' => '\\ElectronicDocumentSearchParameters',
  'FareCalculation.Details' => '\\FareCalculationDetails',
  'GetElectronicDocumentRQ' => '\\GetElectronicDocumentRQ',
  'GetElectronicDocumentRS' => '\\GetElectronicDocumentRS',
  'Identifier.PaymentAccount' => '\\IdentifierPaymentAccount',
  'Identifier.Provider' => '\\IdentifierProvider',
  'Identifier.Reservation' => '\\IdentifierReservation',
  'Miscellaneous.Indicators' => '\\MiscellaneousIndicators',
  'Number.AssociatedDocument' => '\\NumberAssociatedDocument',
  'OptionalService' => '\\OptionalService',
  'Payment.BankCard.ED' => '\\PaymentBankCardED',
  'Payment.BankCheck' => '\\PaymentBankCheck',
  'Payment.Cash' => '\\PaymentCash',
  'Payment.Certficate' => '\\PaymentCertficate',
  'Payment.GovernmentTravel' => '\\PaymentGovernmentTravel',
  'Payment.Invoice' => '\\PaymentInvoice',
  'Payment.Miscellaneous' => '\\PaymentMiscellaneous',
  'Payment.Other' => '\\PaymentOther',
  'Payment.PrepaidTicketAdvise' => '\\PaymentPrepaidTicketAdvise',
  'Payment.RevenueAccounting' => '\\PaymentRevenueAccounting',
  'Payment.TravelDocument' => '\\PaymentTravelDocument',
  'Payment.Voucher' => '\\PaymentVoucher',
  'PaymentAmount' => '\\PaymentAmount',
  'PaymentAmount.Basic' => '\\PaymentAmountBasic',
  'RelatedDocument.Abbreviated' => '\\RelatedDocumentAbbreviated',
  'RelatedDocument.Basic' => '\\RelatedDocumentBasic',
  'RelatedDocument.Details' => '\\RelatedDocumentDetails',
  'RelatedDocument.Details.ED' => '\\RelatedDocumentDetailsED',
  'RelatedDocument.Details.Original.TKT' => '\\RelatedDocumentDetailsOriginalTKT',
  'RelatedDocument.Details.Original.TKT.ED' => '\\RelatedDocumentDetailsOriginalTKTED',
  'Remark.Details' => '\\RemarkDetails',
  'Remark.DetailsWithHeader' => '\\RemarkDetailsWithHeader',
  'Remark.DetailsWithType' => '\\RemarkDetailsWithType',
  'Reservation.Details.ED' => '\\ReservationDetailsED',
  'ServiceCoupon.InvoluntaryReroute' => '\\ServiceCouponInvoluntaryReroute',
  'Tax.Details' => '\\TaxDetails',
  'Tax.Details.Airport' => '\\TaxDetailsAirport',
  'Tax.Details.Domestic' => '\\TaxDetailsDomestic',
  'Tax.Details.ED' => '\\TaxDetailsED',
  'Tax.Misc' => '\\TaxMisc',
  'TaxAmount' => '\\TaxAmount',
  'TaxAmount.Coupon' => '\\TaxAmountCoupon',
  'Taxes.New.Tax' => '\\TaxesNewTax',
  'Ticketing.Agent.ED' => '\\TicketingAgentED',
  'Ticketing.Document.EMD.ED' => '\\TicketingDocumentEMDED',
  'Ticketing.Document.Ticket.ED' => '\\TicketingDocumentTicketED',
  'FareCalculation' => '\\FareCalculation',
  'Ticketing.TransactionInfo.ED' => '\\TicketingTransactionInfoED',
  'TicketingDocument.Affinity.ED' => '\\TicketingDocumentAffinityED',
  'TicketingDocument.Amounts.EMD' => '\\TicketingDocumentAmountsEMD',
  'TicketingDocument.Amounts.Ticket.ED' => '\\TicketingDocumentAmountsTicketED',
  'Amounts.Other.ED' => '\\AmountsOtherED',
  'TicketingDocument.CurrencyConversion' => '\\TicketingDocumentCurrencyConversion',
  'TicketingDocument.Customer.ED' => '\\TicketingDocumentCustomerED',
  'TicketingDocument.Details.EMD.ED' => '\\TicketingDocumentDetailsEMDED',
  'TicketingDocument.Details.Ticket.ED' => '\\TicketingDocumentDetailsTicketED',
  'TicketingDocument.History.ED' => '\\TicketingDocumentHistoryED',
  'TicketingDocument.Indicators.EMD' => '\\TicketingDocumentIndicatorsEMD',
  'TicketingDocument.Miscellaneous.ED' => '\\TicketingDocumentMiscellaneousED',
  'Fee.Details' => '\\FeeDetails',
  'Amount.Basic.BankerSellingRate' => '\\AmountBasicBankerSellingRate',
  'TicketingDocument.Payment' => '\\TicketingDocumentPayment',
  'TicketingDocument.Payment.ED' => '\\TicketingDocumentPaymentED',
  'TicketingDocument.Related' => '\\TicketingDocumentRelated',
  'TicketingDocument.Related.Ticket.ED' => '\\TicketingDocumentRelatedTicketED',
  'TicketingDocument.Remark.ED' => '\\TicketingDocumentRemarkED',
  'TicketingDocument.Remark.EMD' => '\\TicketingDocumentRemarkEMD',
  'TicketingDocument.ServiceCoupon.EMD.ED' => '\\TicketingDocumentServiceCouponEMDED',
  'StartLocation' => '\\StartLocation',
  'EndLocation' => '\\EndLocation',
  'BookingStatus' => '\\BookingStatus',
  'TicketingDocument.ServiceCoupon.Ticket.ED' => '\\TicketingDocumentServiceCouponTicketED',
  'TicketingDocument.Taxes.EMD' => '\\TicketingDocumentTaxesEMD',
  'TicketingDocument.Taxes.New.ED' => '\\TicketingDocumentTaxesNewED',
  'TicketingDocument.Taxes.Ticket.ED' => '\\TicketingDocumentTaxesTicketED',
  'TicketingDocument.ValueCalculation' => '\\TicketingDocumentValueCalculation',
  'DocumentDetailsDisplay' => '\\DocumentDetailsDisplay',
  'DocumentHistoryDisplay' => '\\DocumentHistoryDisplay',
  'SignatureType' => '\\SignatureType',
  'SignatureValueType' => '\\SignatureValueType',
  'SignedInfoType' => '\\SignedInfoType',
  'CanonicalizationMethodType' => '\\CanonicalizationMethodType',
  'SignatureMethodType' => '\\SignatureMethodType',
  'ReferenceType' => '\\ReferenceType',
  'TransformsType' => '\\TransformsType',
  'TransformType' => '\\TransformType',
  'DigestMethodType' => '\\DigestMethodType',
  'KeyInfoType' => '\\KeyInfoType',
  'KeyValueType' => '\\KeyValueType',
  'RetrievalMethodType' => '\\RetrievalMethodType',
  'X509DataType' => '\\X509DataType',
  'X509IssuerSerialType' => '\\X509IssuerSerialType',
  'PGPDataType' => '\\PGPDataType',
  'SPKIDataType' => '\\SPKIDataType',
  'ObjectType' => '\\ObjectType',
  'ManifestType' => '\\ManifestType',
  'SignaturePropertiesType' => '\\SignaturePropertiesType',
  'SignaturePropertyType' => '\\SignaturePropertyType',
  'DSAKeyValueType' => '\\DSAKeyValueType',
  'RSAKeyValueType' => '\\RSAKeyValueType',
  'Envelope' => '\\Envelope',
  'Header' => '\\Header',
  'Body' => '\\Body',
  'Fault' => '\\Fault',
  'detail' => '\\detail',
  'Manifest' => '\\Manifest',
  'Reference' => '\\Reference',
  'Schema' => '\\SchemaCustom',
  'MessageHeader' => '\\MessageHeader',
  'Service' => '\\Service',
  'MessageData' => '\\MessageData',
  'SyncReply' => '\\SyncReply',
  'MessageOrder' => '\\MessageOrder',
  'AckRequested' => '\\AckRequested',
  'Acknowledgment' => '\\Acknowledgment',
  'ErrorList' => '\\ErrorList',
  'Error' => '\\ErrorCustom',
  'StatusResponse' => '\\StatusResponse',
  'StatusRequest' => '\\StatusRequest',
  'sequenceNumber.type' => '\\sequenceNumbertype',
  'PartyId' => '\\PartyId',
  'To' => '\\To',
  'From' => '\\From',
  'Description' => '\\Description',
  'Security' => '\\Security',
  'BinarySecurityToken' => '\\BinarySecurityToken',
);

    /**
     * @param array $options A array of config values
     * @param string $wsdl The wsdl file to use
     */
    public function __construct(array $options = array(), $wsdl = null)
    {
    
  foreach (self::$classmap as $key => $value) {
    if (!isset($options['classmap'][$key])) {
      $options['classmap'][$key] = $value;
    }
  }
      $options = array_merge(array (
  'features' => 1,
), $options);
      if (!$wsdl) {
        $wsdl = 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/fulfillment/TKT_ElectronicDocumentServices_v.1.0.0.wsdl';
      }
      parent::__construct($wsdl, $options);
    }

    /**
     * @param GetElectronicDocumentRQ $body
     * @return GetElectronicDocumentRS
     */
    public function GetElectronicDocumentRQ(GetElectronicDocumentRQ $body)
    {
      return $this->__soapCall('GetElectronicDocumentRQ', array($body));
    }

}
